name: Trigger auto deployment for aca1

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '//**'
    - '.github/workflows/aca1-AutoDeployTrigger-a244727e-9ea5-4f03-8b62-9e84c367d25f.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.ACA1_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.ACA1_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.ACA1_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: acrcustomportaluks001.azurecr.io
          registryUsername: ${{ secrets.ACA1_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.ACA1_REGISTRY_PASSWORD }}
          containerAppName: aca1
          resourceGroup: RG1
          imageToBuild: acrcustomportaluks001.azurecr.io/aca1:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


